### ISSUE TITLE
Keyboard media keys behaviour

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#3]
I was just wondering what the expected result of using the media keys ▶️ ⏸ should be

It used to pause the music and make the room out of sync but I see that this is now catched and the music is restarted by the `running check`
However short pause resumes can still get the room out of sync I think.

Chrome Version 89.0.4389.90 (Official Build) (x86_64)
```
index.06ad6a013cacba2b2863.js:205 new state 8
index.06ad6a013cacba2b2863.js:205 track data {duration: 264.2, genre: "", id: "1233191490", musicProvider: "apple", title: "Down to Earth", …}
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 8
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 8, state: 2}
index.06ad6a013cacba2b2863.js:205 new state 2
index.06ad6a013cacba2b2863.js:205 track data {duration: 264.2, genre: "", id: "1233191490", musicProvider: "apple", title: "Down to Earth", …}
index.06ad6a013cacba2b2863.js:205 doing a skim to 18.977
index.06ad6a013cacba2b2863.js:205 Start time 2021-04-02T06:39:43.462Z
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 2
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 2, state: 6}
index.06ad6a013cacba2b2863.js:205 new state 6
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 6, state: 8}
index.06ad6a013cacba2b2863.js:205 new state 8
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 6
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 8
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 8, state: 2}
index.06ad6a013cacba2b2863.js:205 new state 2
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 2
musickit-mod.js:1334 HIJACKED PLAY ACTIVITY ERROR The scrub() method was called with the SCRUB_END action without a previous SCRUB_START descriptor
MKError.playActivityError @ musickit-mod.js:1334
(anonymous) @ musickit-mod.js:1783
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
PlayActivity.scrub @ musickit-mod.js:1774
(anonymous) @ musickit-mod.js:9786
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
BasePlayer.seekToTime @ musickit-mod.js:9769
(anonymous) @ musickit-mod.js:11417
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
SerialPlayback.seekToTime @ musickit-mod.js:11415
(anonymous) @ musickit-mod.js:12098
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
MusicKitInstance.seekToTime @ musickit-mod.js:12086
r @ index.06ad6a013cacba2b2863.js:205
r @ index.06ad6a013cacba2b2863.js:205
(anonymous) @ musickit-mod.js:6044
Notifications.dispatchEvent @ musickit-mod.js:6043
(anonymous) @ musickit-mod.js:11544
(anonymous) @ musickit-mod.js:6044
Notifications.dispatchEvent @ musickit-mod.js:6043
set @ musickit-mod.js:9641
(anonymous) @ musickit-mod.js:10761
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
AudioPlayer.handleEvent @ musickit-mod.js:10731
index.06ad6a013cacba2b2863.js:205 Failed to seek with error: TypeError: Cannot read property 'hasOwnProperty' of null
    at MusicKitInstance._handlePlaybackError (musickit-mod.js:12315)
    at MusicKitInstance.<anonymous> (musickit-mod.js:12103)
    at musickit-mod.js:918
    at Object.throw (musickit-mod.js:929)
    at rejected (musickit-mod.js:814)
index.06ad6a013cacba2b2863.js:205 Play succeeded with status undefined
2index.06ad6a013cacba2b2863.js:205 running check
```

and another log

```
index.06ad6a013cacba2b2863.js:205 running check
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 2, state: 3}
index.06ad6a013cacba2b2863.js:205 new state 3
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 3
index.06ad6a013cacba2b2863.js:205 running check
index.06ad6a013cacba2b2863.js:205 Should be playing but you're not



index.06ad6a013cacba2b2863.js:205 GENERATING NEW INSTANCE
index.06ad6a013cacba2b2863.js:205 Attempting to play track Down to Earth
index.06ad6a013cacba2b2863.js:205 Queue set successful, attempting to play
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 3, state: 1}
index.06ad6a013cacba2b2863.js:205 new state 1
index.06ad6a013cacba2b2863.js:205 track data {duration: 264.2, genre: "", id: "1233191490", musicProvider: "apple", title: "Down to Earth", …}
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 1
blob:https://boring.fm/2ee966ca-859e-4eb2-8232-5992cdf29adc:1 GET blob:https://boring.fm/2ee966ca-859e-4eb2-8232-5992cdf29adc net::ERR_FILE_NOT_FOUND
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 1, state: 8}
index.06ad6a013cacba2b2863.js:205 new state 8
index.06ad6a013cacba2b2863.js:205 track data {duration: 264.2, genre: "", id: "1233191490", musicProvider: "apple", title: "Down to Earth", …}
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 8
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 8, state: 2}
index.06ad6a013cacba2b2863.js:205 new state 2
index.06ad6a013cacba2b2863.js:205 track data {duration: 264.2, genre: "", id: "1233191490", musicProvider: "apple", title: "Down to Earth", …}
index.06ad6a013cacba2b2863.js:205 doing a skim to 18.977
index.06ad6a013cacba2b2863.js:205 Start time 2021-04-02T06:39:43.462Z
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 2
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 2, state: 6}
index.06ad6a013cacba2b2863.js:205 new state 6
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 6, state: 8}
index.06ad6a013cacba2b2863.js:205 new state 8
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 6
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 8
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 8, state: 2}
index.06ad6a013cacba2b2863.js:205 new state 2
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 2
musickit-mod.js:1334 HIJACKED PLAY ACTIVITY ERROR The scrub() method was called with the SCRUB_END action without a previous SCRUB_START descriptor
MKError.playActivityError @ musickit-mod.js:1334
(anonymous) @ musickit-mod.js:1783
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
PlayActivity.scrub @ musickit-mod.js:1774
(anonymous) @ musickit-mod.js:9786
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
BasePlayer.seekToTime @ musickit-mod.js:9769
(anonymous) @ musickit-mod.js:11417
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
SerialPlayback.seekToTime @ musickit-mod.js:11415
(anonymous) @ musickit-mod.js:12098
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
MusicKitInstance.seekToTime @ musickit-mod.js:12086
r @ index.06ad6a013cacba2b2863.js:205
r @ index.06ad6a013cacba2b2863.js:205
(anonymous) @ musickit-mod.js:6044
Notifications.dispatchEvent @ musickit-mod.js:6043
(anonymous) @ musickit-mod.js:11544
(anonymous) @ musickit-mod.js:6044
Notifications.dispatchEvent @ musickit-mod.js:6043
set @ musickit-mod.js:9641
(anonymous) @ musickit-mod.js:10761
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
AudioPlayer.handleEvent @ musickit-mod.js:10731
index.06ad6a013cacba2b2863.js:205 Failed to seek with error: TypeError: Cannot read property 'hasOwnProperty' of null
    at MusicKitInstance._handlePlaybackError (musickit-mod.js:12315)
    at MusicKitInstance.<anonymous> (musickit-mod.js:12103)
    at musickit-mod.js:918
    at Object.throw (musickit-mod.js:929)
    at rejected (musickit-mod.js:814)
index.06ad6a013cacba2b2863.js:205 Play succeeded with status undefined
13index.06ad6a013cacba2b2863.js:205 running check
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 2, state: 3}
index.06ad6a013cacba2b2863.js:205 new state 3
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 3
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 3, state: 2}
index.06ad6a013cacba2b2863.js:205 new state 2
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 2
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 2, state: 3}
index.06ad6a013cacba2b2863.js:205 new state 3
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 3
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 3, state: 2}
index.06ad6a013cacba2b2863.js:205 new state 2
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 2
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 2, state: 3}
index.06ad6a013cacba2b2863.js:205 new state 3
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 3
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 3, state: 2}
index.06ad6a013cacba2b2863.js:205 new state 2
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 2
12index.06ad6a013cacba2b2863.js:205 running check
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 2, state: 3}
index.06ad6a013cacba2b2863.js:205 new state 3
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 3
index.06ad6a013cacba2b2863.js:205 running check
index.06ad6a013cacba2b2863.js:205 Should be playing but you're not



index.06ad6a013cacba2b2863.js:205 GENERATING NEW INSTANCE
index.06ad6a013cacba2b2863.js:205 Attempting to play track Down to Earth
index.06ad6a013cacba2b2863.js:205 Queue set successful, attempting to play
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 3, state: 1}
index.06ad6a013cacba2b2863.js:205 new state 1
index.06ad6a013cacba2b2863.js:205 track data {duration: 264.2, genre: "", id: "1233191490", musicProvider: "apple", title: "Down to Earth", …}
blob:https://boring.fm/afe7d8c4-5910-420d-bbf7-e2d16b55956a:1 GET blob:https://boring.fm/afe7d8c4-5910-420d-bbf7-e2d16b55956a net::ERR_FILE_NOT_FOUND
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 1
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 1, state: 8}
index.06ad6a013cacba2b2863.js:205 new state 8
index.06ad6a013cacba2b2863.js:205 track data {duration: 264.2, genre: "", id: "1233191490", musicProvider: "apple", title: "Down to Earth", …}
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 8
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 8, state: 2}
index.06ad6a013cacba2b2863.js:205 new state 2
index.06ad6a013cacba2b2863.js:205 track data {duration: 264.2, genre: "", id: "1233191490", musicProvider: "apple", title: "Down to Earth", …}
index.06ad6a013cacba2b2863.js:205 doing a skim to 169.408
index.06ad6a013cacba2b2863.js:205 Start time 2021-04-02T06:39:43.462Z
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 2
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 2, state: 6}
index.06ad6a013cacba2b2863.js:205 new state 6
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 6, state: 8}
index.06ad6a013cacba2b2863.js:205 new state 8
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 6
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 8
index.06ad6a013cacba2b2863.js:195 Player state change {oldState: 8, state: 2}
index.06ad6a013cacba2b2863.js:205 new state 2
index.06ad6a013cacba2b2863.js:205 Setting up background track play checker
index.06ad6a013cacba2b2863.js:205 Current status 2
musickit-mod.js:1334 HIJACKED PLAY ACTIVITY ERROR The scrub() method was called with the SCRUB_END action without a previous SCRUB_START descriptor
MKError.playActivityError @ musickit-mod.js:1334
(anonymous) @ musickit-mod.js:1783
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
PlayActivity.scrub @ musickit-mod.js:1774
(anonymous) @ musickit-mod.js:9786
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
BasePlayer.seekToTime @ musickit-mod.js:9769
(anonymous) @ musickit-mod.js:11417
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
SerialPlayback.seekToTime @ musickit-mod.js:11415
(anonymous) @ musickit-mod.js:12098
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
MusicKitInstance.seekToTime @ musickit-mod.js:12086
r @ index.06ad6a013cacba2b2863.js:205
r @ index.06ad6a013cacba2b2863.js:205
(anonymous) @ musickit-mod.js:6044
Notifications.dispatchEvent @ musickit-mod.js:6043
(anonymous) @ musickit-mod.js:11544
(anonymous) @ musickit-mod.js:6044
Notifications.dispatchEvent @ musickit-mod.js:6043
set @ musickit-mod.js:9641
(anonymous) @ musickit-mod.js:10761
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
AudioPlayer.handleEvent @ musickit-mod.js:10731
index.06ad6a013cacba2b2863.js:205 Failed to seek with error: TypeError: Cannot read property 'hasOwnProperty' of null
    at MusicKitInstance._handlePlaybackError (musickit-mod.js:12315)
    at MusicKitInstance.<anonymous> (musickit-mod.js:12103)
    at musickit-mod.js:918
    at Object.throw (musickit-mod.js:929)
    at rejected (musickit-mod.js:814)
musickit-mod.js:8966 Uncaught (in promise) DOMException: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'.
    at Buffer.<anonymous> (https://boring.fm/musickit-mod.js:8966:65)
    at https://boring.fm/musickit-mod.js:918:21
    at Object.next (https://boring.fm/musickit-mod.js:929:11)
    at https://boring.fm/musickit-mod.js:827:38
    at new Promise (<anonymous>)
    at __awaiter (https://boring.fm/musickit-mod.js:803:12)
    at Buffer.dequeueBufferAction (https://boring.fm/musickit-mod.js:8955:18)
    at Buffer.<anonymous> (https://boring.fm/musickit-mod.js:8972:51)
    at https://boring.fm/musickit-mod.js:918:21
    at Object.next (https://boring.fm/musickit-mod.js:929:11)
(anonymous) @ musickit-mod.js:8966
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
Buffer.dequeueBufferAction @ musickit-mod.js:8955
(anonymous) @ musickit-mod.js:8972
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
Buffer.dequeueBufferAction @ musickit-mod.js:8955
index.06ad6a013cacba2b2863.js:205 Play succeeded with status undefined
3index.06ad6a013cacba2b2863.js:205 running check
```

**Comment by t3dotgg** [comment]
Funny enough I was using the play/pause media keys to test the "force retry" code. Ideally these will be suppressed entirely - good catch :)

**Comment by t3dotgg** [comment]
Just did way too much research on this, sadly it is not something I can take control of from spotify and apple. Overrides had no luck and neither let me disable the behavior :(

Closing as a wontfix
