### ISSUE TITLE
Queue set failed CONTENT_UNAVAILABLE: The requested content is not available.

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#6]
Maybe because a track is region-limited?
but I guess this should be handled instead of that `Uncaught (in promise) TypeError: e.includes is not a function`

```

index.033b43475d35bf41d71a.js:195 Player state change Object
index.033b43475d35bf41d71a.js:205 new state 2
index.033b43475d35bf41d71a.js:195 track data Object
index.033b43475d35bf41d71a.js:195 doing a skim to 239.395
index.033b43475d35bf41d71a.js:195 Start time 2021-04-02T14:29:15.000Z
index.033b43475d35bf41d71a.js:195 Player state change Object
index.033b43475d35bf41d71a.js:205 new state 8
index.033b43475d35bf41d71a.js:195 Player state change Object
index.033b43475d35bf41d71a.js:205 new state 6
index.033b43475d35bf41d71a.js:195 Player state change Object
index.033b43475d35bf41d71a.js:205 new state 8
index.033b43475d35bf41d71a.js:195 Player state change Object
index.033b43475d35bf41d71a.js:205 new state 2
index.033b43475d35bf41d71a.js:195 Seek succeeded with status undefined
23index.033b43475d35bf41d71a.js:205 running check
index.033b43475d35bf41d71a.js:195 Attempting to play track Red Runner
index.033b43475d35bf41d71a.js:205 Complete now playing update Object
index.033b43475d35bf41d71a.js:195 Player state change Object
index.033b43475d35bf41d71a.js:205 new state 3
index.033b43475d35bf41d71a.js:195 track data Object
index.033b43475d35bf41d71a.js:195 Player state change Object
index.033b43475d35bf41d71a.js:205 new state 5
index.033b43475d35bf41d71a.js:195 track data Object
index.033b43475d35bf41d71a.js:195 Player state change Object
index.033b43475d35bf41d71a.js:205 new state 10
index.033b43475d35bf41d71a.js:195 track data Object
index.033b43475d35bf41d71a.js:195 Queue set failed CONTENT_UNAVAILABLE: The requested content is not available.
    at API.<anonymous> (https://boring.fm/musickit-mod.js:5937:29)
    at https://boring.fm/musickit-mod.js:918:21
    at Object.next (https://boring.fm/musickit-mod.js:929:11)
    at fulfilled (https://boring.fm/musickit-mod.js:806:18)
index.033b43475d35bf41d71a.js:195 Uncaught (in promise) TypeError: e.includes is not a function
    at index.033b43475d35bf41d71a.js:195
index.033b43475d35bf41d71a.js:205 running check
index.033b43475d35bf41d71a.js:205 Should be playing but you're not



index.033b43475d35bf41d71a.js:205 Attempting to stop
index.033b43475d35bf41d71a.js:205 GENERATING NEW INSTANCE
index.033b43475d35bf41d71a.js:195 Attempting to play track Red Runner
index.033b43475d35bf41d71a.js:195 Queue set failed CONTENT_UNAVAILABLE: The requested content is not available.
    at API.<anonymous> (https://boring.fm/musickit-mod.js:5937:29)
    at https://boring.fm/musickit-mod.js:918:21
    at Object.next (https://boring.fm/musickit-mod.js:929:11)
    at fulfilled (https://boring.fm/musickit-mod.js:806:18)
index.033b43475d35bf41d71a.js:195 Player state change Object
index.033b43475d35bf41d71a.js:205 new state 6
index.033b43475d35bf41d71a.js:195 track data Object
index.033b43475d35bf41d71a.js:195 track data Object
index.033b43475d35bf41d71a.js:195 Uncaught (in promise) TypeError: e.includes is not a function
    at index.033b43475d35bf41d71a.js:195
48index.033b43475d35bf41d71a.js:205 running check
index.033b43475d35bf41d71a.js:195 Attempting to play track Minimal (Dj Koze Mix)
index.033b43475d35bf41d71a.js:205 Complete now playing update {duration: 365.809, genre: "", id: "596233902", musicProvider: "apple", title: "Minimal (Dj Koze Mix)", …}
index.033b43475d35bf41d71a.js:195 Queue set probably successful, output: Queue {_registry: {…}, _itemIDs: Array(1), _unshuffledIDs: {…}, _items: Array(1), _isRestricted: false, …}
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 6, state: 1}
index.033b43475d35bf41d71a.js:205 new state 1
index.033b43475d35bf41d71a.js:195 track data {duration: 247.68, genre: "", id: "1523815995", musicProvider: "apple", title: "Red Runner", …}
index.033b43475d35bf41d71a.js:195 track data {duration: 247.68, genre: "", id: "1523815995", musicProvider: "apple", title: "Red Runner", …}
index.033b43475d35bf41d71a.js:195 track data {duration: 365.809, genre: "", id: "596233902", musicProvider: "apple", title: "Minimal (Dj Koze Mix)", …}
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 1, state: 8}
index.033b43475d35bf41d71a.js:205 new state 8
index.033b43475d35bf41d71a.js:195 track data {duration: 247.68, genre: "", id: "1523815995", musicProvider: "apple", title: "Red Runner", …}
index.033b43475d35bf41d71a.js:195 track data {duration: 247.68, genre: "", id: "1523815995", musicProvider: "apple", title: "Red Runner", …}
index.033b43475d35bf41d71a.js:195 track data {duration: 365.809, genre: "", id: "596233902", musicProvider: "apple", title: "Minimal (Dj Koze Mix)", …}
index.033b43475d35bf41d71a.js:195 Play succeeded with status undefined
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 8, state: 2}
index.033b43475d35bf41d71a.js:205 new state 2
index.033b43475d35bf41d71a.js:195 track data {duration: 247.68, genre: "", id: "1523815995", musicProvider: "apple", title: "Red Runner", …}
index.033b43475d35bf41d71a.js:195 doing a skim to 252.783
index.033b43475d35bf41d71a.js:195 Start time 2021-04-02T14:35:10.387Z
index.033b43475d35bf41d71a.js:195 track data {duration: 365.809, genre: "", id: "596233902", musicProvider: "apple", title: "Minimal (Dj Koze Mix)", …}
index.033b43475d35bf41d71a.js:195 doing a skim to 5.118
index.033b43475d35bf41d71a.js:195 Start time 2021-04-02T14:39:18.056Z
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 2, state: 6}
index.033b43475d35bf41d71a.js:205 new state 6
index.033b43475d35bf41d71a.js:195 track data {duration: 247.68, genre: "", id: "1523815995", musicProvider: "apple", title: "Red Runner", …}
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 6, state: 8}
index.033b43475d35bf41d71a.js:205 new state 8
index.033b43475d35bf41d71a.js:195 track data {duration: 247.68, genre: "", id: "1523815995", musicProvider: "apple", title: "Red Runner", …}
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 8, state: 2}
index.033b43475d35bf41d71a.js:205 new state 2
index.033b43475d35bf41d71a.js:195 track data {duration: 247.68, genre: "", id: "1523815995", musicProvider: "apple", title: "Red Runner", …}
index.033b43475d35bf41d71a.js:195 doing a skim to 252.804
index.033b43475d35bf41d71a.js:195 Start time 2021-04-02T14:35:10.387Z
index.033b43475d35bf41d71a.js:195 Seek succeeded with status undefined
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 2, state: 8}
index.033b43475d35bf41d71a.js:205 new state 8
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 8, state: 6}
index.033b43475d35bf41d71a.js:205 new state 6
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 6, state: 8}
index.033b43475d35bf41d71a.js:205 new state 8
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 8, state: 2}
index.033b43475d35bf41d71a.js:205 new state 2
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 2, state: 6}
index.033b43475d35bf41d71a.js:205 new state 6
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 6, state: 8}
index.033b43475d35bf41d71a.js:205 new state 8
index.033b43475d35bf41d71a.js:195 Player state change {oldState: 8, state: 2}
index.033b43475d35bf41d71a.js:205 new state 2
musickit-mod.js:1334 HIJACKED PLAY ACTIVITY ERROR The scrub() method was called with the SCRUB_END action without a previous SCRUB_START descriptor
MKError.playActivityError @ musickit-mod.js:1334
(anonymous) @ musickit-mod.js:1783
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
PlayActivity.scrub @ musickit-mod.js:1774
(anonymous) @ musickit-mod.js:9786
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
fulfilled @ musickit-mod.js:806
Promise.then (async)
step @ musickit-mod.js:825
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
BasePlayer.seekToTime @ musickit-mod.js:9769
(anonymous) @ musickit-mod.js:11417
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
SerialPlayback.seekToTime @ musickit-mod.js:11415
(anonymous) @ musickit-mod.js:12098
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
MusicKitInstance.seekToTime @ musickit-mod.js:12086
r @ index.033b43475d35bf41d71a.js:195
r @ index.033b43475d35bf41d71a.js:195
(anonymous) @ musickit-mod.js:6044
Notifications.dispatchEvent @ musickit-mod.js:6043
(anonymous) @ musickit-mod.js:11544
(anonymous) @ musickit-mod.js:6044
Notifications.dispatchEvent @ musickit-mod.js:6043
set @ musickit-mod.js:9641
(anonymous) @ musickit-mod.js:10761
(anonymous) @ musickit-mod.js:918
(anonymous) @ musickit-mod.js:929
(anonymous) @ musickit-mod.js:827
__awaiter @ musickit-mod.js:803
AudioPlayer.handleEvent @ musickit-mod.js:10731
index.033b43475d35bf41d71a.js:195 Failed to seek with error: TypeError: Cannot read property 'hasOwnProperty' of null
    at MusicKitInstance._handlePlaybackError (VM133 musickit-mod.js:12315)
    at MusicKitInstance.<anonymous> (VM133 musickit-mod.js:12103)
    at VM133 musickit-mod.js:918
    at Object.throw (VM133 musickit-mod.js:929)
    at rejected (VM133 musickit-mod.js:814)
index.033b43475d35bf41d71a.js:195 Seek succeeded with status undefined
19index.033b43475d35bf41d71a.js:205 running check
```

**Comment by t3dotgg** [comment]
Definitely fixed this one now :)
